---
name: ((minio_deployment_name))

releases:
- name: minio
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

variables:
- name: minio_accesskey
  type: password
- name: minio_secretkey
  type: password

instance_groups:
- name: minio
  azs: [z1]
  instances: 1
  jobs:
  - name: minio-server
    release: minio
    templates:
    - name: minio-server
    provides:
      minio-server: {as: minio-link}
    properties:
      credential:
        accesskey: ((minio_accesskey))
        secretkey: ((minio_secretkey))
      port: 9000
  networks:
  - name: default
  vm_type: default
  persistent_disk_type: 2048
  stemcell: default

- name: tests
  azs: [z1]
  instances: 1
  lifecycle: errand
  post_deploy: true
  jobs:
  - name: smoke-tests
    release: minio
    templates:
    - name: smoke-tests
    consumes:
      minio: {from: minio-link}
  networks:
  - name: default
  vm_type: default
  persistent_disk_type: 2048
  env:
    persistent_disk_fs: xfs
  stemcell: default

- name: bucket-seeding # To create default buckets after manifest-deploy
  azs: [z1]
  instances: 1
  lifecycle: errand
  post_deploy: true
  jobs:
  - name: mc
    release: minio
    templates:
    - name: mc
    consumes:
      minio: {from: minio-link}
    properties:
      script: |
        #!/bin/sh
        mc mb myminio/bucket1
        mc mb myminio/bucket2
        mc mb myminio/bucket3
        mc mb myminio/bucket3
  networks:
  - name: default
  vm_type: default
  persistent_disk_type: 2048
  stemcell: default

update:
  canaries: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  max_in_flight: 1

