{
 "title": "App Dashboard",
 "description": "App Dashboard",
 "tags": [ "healthwatch" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "deployment", "label": "Deployment", "query": { "query": "query_result(container_age)" } },
   {
    "name": "org",
    "label": "org",
    "query": {
     "query": "query_result(container_age{deployment=~\"$deployment\"})"
    }
   },
   {
    "name": "space",
    "label": "space",
    "query": {
     "query": "query_result(container_age{deployment=~\"$deployment\", organization_name=~\"$org\"})"
    }
   },
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "query_result(container_age{deployment=~\"$deployment\", organization_name=~\"$org\", space_name=~\"$space\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "App Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "## Description\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu{deployment=~\"$deployment\",organization_name=~\"$org\",space_name=~\"$space\",app_name=~\"$app\",process_type=\"web\"}",
     "legendFormat": "{{app_name}}-{{instance_id}}"
    }
   ]
  },
  {
   "title": "cpu entitlement",
   "type": "graph",
   "description": "## Description",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu_entitlement{deployment=~\"$deployment\",organization_name=~\"$org\",space_name=~\"$space\",app_name=~\"$app\",process_type=\"web\"}",
     "legendFormat": "{{app_name}}-{{instance_id}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "## Description",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "memory{deployment=~\"$deployment\",organization_name=~\"$org\",space_name=~\"$space\",app_name=~\"$app\",process_type=\"web\"}",
     "legendFormat": "{{app_name}}-{{instance_id}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "description": "## Description",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "disk{deployment=~\"$deployment\",organization_name=~\"$org\",space_name=~\"$space\",app_name=~\"$app\",process_type=\"web\"}",
     "legendFormat": "{{app_name}}-{{instance_id}}"
    }
   ]
  }
 ]
}