{
 "title": "App Dashboard-MetricStore",
 "description": "App Dashboard-MetricStore",
 "tags": [ "healthwatch" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "deployment", "label": "Deployment", "query": { "query": "query_result(container_age)" } },
   {
    "name": "org",
    "label": "org",
    "query": {
     "query": "query_result(container_age{deployment=~\"$deployment\"})"
    }
   },
   {
    "name": "space",
    "label": "space",
    "query": {
     "query": "query_result(container_age{deployment=~\"$deployment\", organization_name=~\"$org\"})"
    }
   },
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "query_result(container_age{deployment=~\"$deployment\", organization_name=~\"$org\", space_name=~\"$space\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 21, "x": 0, "y": 0 },
   "options": {
    "content": "# App metrics from metric-store \n\nQuering the Metric Store: [https://docs.vmware.com/en/Metric-Store/1.6/metric-store/GUID-using.html](https://docs.vmware.com/en/Metric-Store/1.6/metric-store/GUID-using.html/)"
   }
  },
  {
   "title": "HTTP Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "http_duration_seconds_bucket_raw_data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "http_duration_seconds_bucket{organization_name=~\"$org\", space_name=~\"$space\", app_name=\"$app\"}",
     "legendFormat": "{{le}} bucket"
    }
   ]
  },
  {
   "title": "http_duration_seconds_bucket_histogran_95_percentile",
   "type": "heatmap",
   "description": "\n",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(http_duration_seconds_bucket{organization_name=~\"$org\", space_name=~\"$space\", app_name=\"$app\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_total per min",
   "type": "timeseries",
   "description": "## Description",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(http_total{organization_name=~\"$org\", space_name=~\"$space\", app_name=\"$app\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}