{
 "title": "PAS 2.4 KPIs and KCSIs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Healthy Alerts", "type": "alertlist", "gridPos": { "h": 18, "w": 8, "x": 0, "y": 0 } },
  { "title": "Pending Alerts", "type": "alertlist", "gridPos": { "h": 18, "w": 8, "x": 8, "y": 0 } },
  { "title": "Critical Alerts", "type": "alertlist", "gridPos": { "h": 18, "w": 8, "x": 16, "y": 0 } },
  {
   "title": "Diego",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true
  },
  {
   "title": "Available Free Chunks",
   "type": "graph",
   "description": "The current number of calculated 4-GB chunks of free memory across all cells.\n\nThis derived metric is recommended for automating and monitoring platform scaling. Insufficient free chunks of memory can prevent pushing and scaling apps. Monitoring the amount of free chunks remaining is a more valuable indicator of impending cf push errors due to lack of memory than relying on the Memory Remaining metrics alone.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(floor(CapacityRemainingMemory / 4096))",
     "legendFormat": "Available 4GB Free Chunks"
    }
   ]
  },
  {
   "title": "Diego Cell Container Capacity",
   "type": "graph",
   "description": "Percentage of remaining container capacity for a given cell. Monitor this derived metric across all cells in a deployment. \n\nThe metric rep.CapacityRemainingContainers indicates the remaining number of containers this cell can host.\nThe metric by rep.CapacityTotalContainer indicates the total number of containers this cell can host.\n\nA best practice deployment of Cloud Foundry includes three availability zones (AZs). For these types of deployments, Pivotal recommends that you have enough capacity to suffer failure of an entire AZ. \n\nThe Recommended threshold assumes a three-AZ configuration. Adjust the threshold percentage if you have more or fewer AZs.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(CapacityRemainingContainers{origin=\"rep\"}) by (index) / avg(CapacityTotalContainers{origin=\"rep\"}) by (index)",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Diego Cell Disk Capacity",
   "type": "graph",
   "description": "Percentage of remaining disk capacity for a given cell. Monitor this derived metric across all cells in a deployment. \n\nThe metric rep.CapacityRemainingDisk indicates the remaining amount in MiB of disk available for this cell to allocate to containers.\nThe metric rep.CapacityTotalDisk indicates the total amount in MiB of disk available for this cell to allocate to containers.\n\nA best practice deployment of Cloud Foundry includes three availability zones (AZs). For these types of deployments, Pivotal recommends that you have enough capacity to suffer failure of an entire AZ. \n\nThe Recommended threshold assumes a three-AZ configuration. Adjust the threshold percentage if you have more or fewer AZs.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(CapacityRemainingDisk{origin=\"rep\"}) by (index) / avg(CapacityTotalDisk{origin=\"rep\"}) by (index)",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Diego Cell Memory Capacity",
   "type": "graph",
   "description": "Percentage of remaining memory capacity for a given cell. Monitor this derived metric across all cells in a deployment. \n\nThe metric rep.CapacityRemainingMemory indicates the remaining amount in MiB of memory available for this cell to allocate to containers.\nThe metric rep.CapacityTotalMemory indicates the total amount in MiB of memory available for this cell to allocate to containers.\n\nA best practice deployment of Cloud Foundry includes three availability zones (AZs). For these types of deployments, Pivotal recommends that you have enough capacity to suffer failure of an entire AZ. \n\nThe Recommended threshold assumes a three-AZ configuration. Adjust the threshold percentage if you have more or fewer AZs.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(CapacityRemainingMemory{origin=\"rep\"}) by (index) / avg(CapacityTotalMemory{origin=\"rep\"}) by (index)",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Available Containers",
   "type": "graph",
   "description": "Available number of containers.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "min(avg(CapacityRemainingContainers{origin=\"rep\"}) by(deployment, expored_job, index))",
     "legendFormat": "Cell with Least Available Containers"
    },
    {
     "expr": "max(avg(CapacityRemainingContainers{origin=\"rep\"}) by(deployment, expored_job, index))",
     "legendFormat": "Cell with Most Available Containers"
    },
    {
     "expr": "sum(avg(CapacityRemainingContainers{origin=\"rep\"}) by(deployment, expored_job, index))",
     "legendFormat": "Total Available Containers"
    }
   ]
  },
  {
   "title": "Available Disk",
   "type": "graph",
   "description": "Available MiB of disk to allocate to containers.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "min(avg(CapacityRemainingDisk{origin=\"rep\"}) by(deployment, expored_job, index))",
     "legendFormat": "Cell with Least Available Disk"
    },
    {
     "expr": "max(avg(CapacityRemainingDisk{origin=\"rep\"}) by(deployment, expored_job, index))",
     "legendFormat": "Cell with Most Available Disk"
    },
    {
     "expr": "sum(avg(CapacityRemainingDisk{origin=\"rep\"}) by(deployment, expored_job, index))",
     "legendFormat": "Total Available Disk"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "description": "Available MiB of memory to allocate to containers.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "min(avg(CapacityRemainingMemory{origin=\"rep\"}) by(deployment, exported_job, index))",
     "legendFormat": "Cell with Least Available Memory"
    },
    {
     "expr": "max(avg(CapacityRemainingMemory{origin=\"rep\"}) by(deployment, exported_job, index))",
     "legendFormat": "Cell with Most Available Memory"
    },
    {
     "expr": "sum(avg(CapacityRemainingMemory{origin=\"rep\"}) by(deployment, exported_job, index))",
     "legendFormat": "Total Available Available Memory"
    }
   ]
  },
  {
   "title": "BBS Convergence Duration",
   "type": "graph",
   "description": "Max time in nanoseconds that the BBS took to run its LRP and Task convergence pass. Emitted when LRP and Task convergence runs.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "ConvergenceLRPDuration{origin=\"bbs\"}",
     "legendFormat": "LRPs"
    },
    {
     "expr": "ConvergenceTaskDuration{origin=\"bbs\"}",
     "legendFormat": "Tasks"
    }
   ]
  },
  {
   "title": "BBS Requests per Second (max)",
   "type": "graph",
   "description": "Max number of requests per second received by the BBS.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(RequestCount{origin=\"bbs\"}[$__interval] offset 1m))",
     "legendFormat": "Req/Sec"
    }
   ]
  },
  {
   "title": "BBS Request Latency",
   "type": "graph",
   "description": "Max time in nanoseconds that the BBS took to handle requests to its API endpoints.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "RequestLatency{origin=\"bbs\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "CC and Diego in Sync",
   "type": "graph",
   "description": "Indicates if the cf-apps Domain is up-to-date, meaning that CF App requests from Cloud Controller are synchronized to bbs.LRPsDesired (Diego-desired AIs) for execution.\n1 means cf-apps Domain is up-to-date\nNo data received means cf-apps Domain is not up-to-date\nUse: If the cf-apps Domain does not stay up-to-date, changes requested in the Cloud Controller are not guaranteed to propagate throughout the system. If the Cloud Controller and Diego are out of sync, then apps running could vary from those desired. ",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Domain_cf_apps{origin=\"bbs\"}",
     "legendFormat": "In Sync (last 5m)"
    }
   ]
  },
  {
   "title": "CC 5xx Responses per Second (max)",
   "type": "graph",
   "description": "Max number of CC's HTTP 5xx responses per second.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(\n  rate(http_status_5XX{origin=\"cc\"}[5m] offset 1m)\n  or\n  0 * absent(http_status_5XX{origin=\"cc\"})\n)",
     "legendFormat": "5xx resp/sec"
    }
   ]
  },
  {
   "title": "CC Job Queue Length (max)",
   "type": "graph",
   "description": "Max number of background jobs in the queues that have yet to run for the first time.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(job_queue_length_total{origin=\"cc\"})",
     "legendFormat": "Length"
    }
   ]
  },
  {
   "title": "CC Requests Completed per Second (max)",
   "type": "graph",
   "description": "Max number of requests per second received by the Cloud Controller.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(requests_completed{origin=\"cc\"}[$__interval] offset 1m))",
     "legendFormat": "Req/sec"
    }
   ]
  },
  {
   "title": "Cell Rep Time to Sync",
   "type": "graph",
   "description": "Time in ns that the Diego Cell Rep took to sync the ActualLRPs that it claimed with its actual garden containers. \n\nUse: Sync times that are too high can indicate issues with the BBS. ",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "RepBulkSyncDuration{origin=\"rep\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "LRPs Velocity (max)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(LRPsDesired{origin=\"bbs\"}[$__interval] offset 1m))",
     "legendFormat": "LRPs Desired"
    },
    {
     "expr": "max(rate(LRPsRunning{origin=\"bbs\"}[$__interval] offset 1m))",
     "legendFormat": "LRPs Running"
    }
   ]
  },
  {
   "title": "Auctions per Second (max)",
   "type": "graph",
   "description": "Max number of LRP instances and Tasks that the auctioneer successfully placed on Diego cells per second",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(AuctioneerLRPAuctionsStarted{origin=\"auctioneer\"}[5m] offset 1m))",
     "legendFormat": "LRPs"
    },
    {
     "expr": "avg(rate(AuctioneerTaskAuctionsStarted{origin=\"auctioneer\"}[5m] offset 1m))",
     "legendFormat": "Tasks"
    }
   ]
  },
  {
   "title": "Fetch States Duration (max)",
   "type": "graph",
   "description": "Max time in nanoseconds that the auctioneer took to fetch state from all the cells when running its auction.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max(AuctioneerFetchStatesDuration{origin=\"auctioneer\"})",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Auctions",
   "type": "graph",
   "description": "Cumulative number of LRP instances and Tasks that the auctioneer successfully of failed to place on Diego cells.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(increase(AuctioneerLRPAuctionsStarted{origin=\"auctioneer\"}[1m] offset 1m)[5m:])",
     "legendFormat": "Started LRPs"
    },
    {
     "expr": "avg_over_time(increase(AuctioneerLRPAuctionsFailed{origin=\"auctioneer\"}[1m] offset 1m)[5m:])",
     "legendFormat": "Failed LRPs"
    },
    {
     "expr": "avg_over_time(increase(AuctioneerTaskAuctionsStarted{origin=\"auctioneer\"}[1m] offset 1m)[5m:])",
     "legendFormat": "Started Tasks"
    },
    {
     "expr": "avg_over_time(increase(AuctioneerTaskAuctionsFailed{origin=\"auctioneer\"}[1m] offset 1m)[5m:])",
     "legendFormat": "Failed Tasks"
    }
   ]
  },
  {
   "title": "LRPs Extra",
   "type": "graph",
   "description": "Total number of LRP instances that are no longer desired but still have a BBS record. When Diego wants to add more apps, the BBS sends a request to the auctioneer to spin up additional LRPs. LRPsExtra is the total number of LRP instances that are no longer desired but still have a BBS record. \n",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "LRPsExtra{origin=\"bbs\"}",
     "legendFormat": "Extra LRPs"
    }
   ]
  },
  {
   "title": "LRPs Missing",
   "type": "graph",
   "description": "Total number of LRP instances that are desired but have no record in the BBS. When Diego wants to add more apps, the BBS sends a request to the auctioneer to spin up additional LRPs. LRPsMissing is the total number of LRP instances that are desired but have no BBS record. \n\nUse: If Diego has less LRP running than expected, there may be problems with the BBS.\n\nAn app push with many instances can temporarily spike this metric. However, a sustained spike in bbs.LRPsMissing is unusual and should be investigated. ",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "LRPsMissing{origin=\"bbs\"}",
     "legendFormat": "Missing LRPs"
    }
   ]
  },
  {
   "title": "LRPs Crashed",
   "type": "graph",
   "description": "Total number of LRP instances that have crashed. \n\nUse: Indicates how many instances in the deployment are in a crashed state. An increase in bbs.CrashedActualLRPs can indicate several problems, from a bad app with many instances associated, to a platform issue that is resulting in app crashes. Use this metric to help create a baseline for your deployment. After you have a baseline, you can create a deployment-specific alert to notify of a spike in crashes above the trend line. Tune alert values to your deployment. ",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "CrashedActualLRPs{origin=\"bbs\"}",
     "legendFormat": "Crashed LRPs"
    }
   ]
  },
  {
   "title": "Change in LRPs over 1h",
   "type": "graph",
   "description": "Rate of change in app instances being started or stopped on the platform. It is derived from bbs.LRPsRunning and represents the total number of LRP instances that are running on Diego cells. \n\nUse: Delta reflects upward or downward trend for app instances started or stopped. Helps to provide a picture of the overall growth trend of the environment for capacity planning. You may want to alert on delta values outside of the expected range. ",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(LRPsRunning{origin=\"bbs\"}[1h] offset 1m)",
     "legendFormat": "Running LRPs Delta Over 1h"
    }
   ]
  },
  {
   "title": "Unhealthy Cells",
   "type": "graph",
   "description": "Whether the cell has failed to pass its healthcheck against the garden backend.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "UnhealthyCell{origin=\"rep\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Active Locks",
   "type": "graph",
   "description": "Total count of how many locks the system components are holding. \n\nUse: If the ActiveLocks count is not equal to the expected value, there is likely a problem with Diego. ",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ActiveLocks{origin=\"locket\"}",
     "legendFormat": "Active Locks {{index}}"
    }
   ]
  },
  {
   "title": "Lock Held by BBS",
   "type": "graph",
   "description": "Whether a BBS instance holds the expected BBS lock (in Locket). 1 means the active BBS server holds the lock, and 0 means the lock was lost. \n\nUse: This metric is complimentary to Active Locks, and it offers a BBS-level version of the Locket metrics. Although it is emitted per BBS instance, only 1 active lock is held by BBS. Therefore, the expected value is 1. The metric may occasionally be 0 when the BBS instances are performing a leader transition, but a prolonged value of 0 indicates an issue with BBS. ",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "LockHeld{origin=\"bbs\"}",
     "legendFormat": "BBS Lock Held"
    }
   ]
  },
  {
   "title": "Lock Held by Auctioneer",
   "type": "graph",
   "description": "Whether an Auctioneer instance holds the expected Auctioneer lock (in Locket). 1 means the active Auctioneer holds the lock, and 0 means the lock was lost. \n\nUse: This metric is complimentary to Active Locks, and it offers an Auctioneer-level version of the Locket metrics. Although it is emitted per Auctioneer instance, only 1 active lock is held by Auctioneer. Therefore, the expected value is 1. The metric may occasionally be 0 when the Auctioneer instances are performing a leader transition, but a prolonged value of 0 indicates an issue with Auctioneer. ",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "LockHeld{origin=\"auctioneer\"}",
     "legendFormat": "Auctioneer Lock Held"
    }
   ]
  },
  {
   "title": "Active Presences",
   "type": "graph",
   "description": "Total count of active presences. Presences are defined as the registration records that the cells maintain to advertise themselves to the platform. \n\nUse: If the Active Presences count is far from the expected, there might be a problem with Diego. \n\nThe number of active presences varies according to the number of cells deployed. Therefore, during purposeful scale adjustments to PAS, this alerting threshold should be adjusted.\nEstablish an initial threshold by observing the historical trends for the deployment over a brief period of time, Increase the threshold as more cells are deployed. During a rolling deploy, this metric shows variance during the BOSH lifecycle when cells are evacuated and restarted. Tolerable variance is within the bounds of the BOSH max inflight range for the instance group. ",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ActivePresences{origin=\"locket\"}",
     "legendFormat": "Active Presences"
    }
   ]
  },
  {
   "title": "Loggregator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages per Second Received/Dropped by Doppler Listeners (max)",
     "type": "graph",
     "description": "Max number of messages received & dropped across all of Doppler listeners per second.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(rate(ingress{origin=\"loggregator.doppler\"}[$__interval] offset 1m))",
       "legendFormat": "Received"
      },
      {
       "expr": "max(rate(dropped{origin=\"loggregator.doppler\"}[$__interval] offset 1m))",
       "legendFormat": "Dropped"
      }
     ]
    },
    {
     "title": "Log Transport Loss Rate",
     "type": "graph",
     "description": "This derived value represents the loss rate occurring as messages are transported from the Metron Agent components (log ingress point) through the Doppler components to the firehose endpoints. Metric loggregator.doppler.ingress represents the number of messages entering Dopplers for transport through the firehose, and loggregator.doppler.dropped represents the number of messages dropped without delivery. Messages include the combined stream of logs from all apps and the metrics data from Cloud Foundry components.\n\nExcessive dropped messages can indicate the Dopplers and/or Traffic Controllers are not processing messages fast enough. \n\nThe recommended scaling indicator is to look at the total dropped as a percentage of the total throughput and scale if the derived loss rate value grows greater than 1%.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(dropped{origin=\"loggregator.doppler\"}) / sum(ingress{origin=\"loggregator.doppler\"})",
       "legendFormat": "Loss Rate"
      }
     ]
    },
    {
     "title": "Message Rate",
     "type": "graph",
     "description": "This derived value represents the average rate of envelopes (messages) per Doppler instance. Deriving this into a per-Doppler envelopes-per-second, or envelopes-per-minute, rate can indicate the need to scale when Doppler instances are at their recommended maximum load.\n\nThe recommended scaling indicator is to look at the average load on the Doppler instances, and increase the number of Doppler instances when the derived rate is 16,000 envelopes per second.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ingress{origin=\"loggregator.doppler\"}[$__interval] offset 1m)) / count(ingress{origin=\"loggregator.doppler\"})",
       "legendFormat": "Message Rate"
      }
     ]
    },
    {
     "title": "Slow Consumer Drops per Second",
     "type": "graph",
     "description": "Within PAS, metrics and logs enter the Firehose for transport and exit out of the platform through a consumer nozzle. If the consuming downstream system fails to keep up with the exiting stream of metrics, the Firehose is forced to close the connection to protect itself from back-pressure. The Firehose increments slow_consumer with each connection that it closes because a consumer could not keep up.\n\nThis metric indicates that a Firehose consumer, such as a monitoring tool nozzle, is ingesting Firehose messages too slowly. If this number is anomalous, it may result in the downstream monitoring tool not having all expected data, even though that data was successfully transported through the Firehose.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(doppler_proxy_slow_consumer{origin=\"loggregator.trafficcontroller\"}[$__interval] offset 1m)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "RLP Egress Dropped per Second",
     "type": "graph",
     "description": "Within PAS, logs and metrics enter Loggregator for transport and then egress through the Reverse Log Proxy (RLP). The RLP drops messages when consumers of the RLP, such as monitoring tool nozzles, ingest the exiting stream of logs and metrics too slowly.\n\nThis metric indicates that a consumer of logs and metrics from the RLP, such as a monitoring tool nozzle, is ingesting RLP messages too slowly.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(dropped{origin=\"loggregator.rlp\", direction=\"egress\"}[$__interval] offset 1m)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Doppler Subscriptions",
     "type": "graph",
     "description": "Within PAS, the Reverse Log Proxy (RLP) limits the number of subscriptions. A subscription is a consumer of the RLP so this metric concerns the number of concurrent consumer of an RLP instance. The maximum subscription count is 1000 per RLP.\n\nThis metric indicates that the RLP has reached its concurrent consumer limit",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "subscriptions{origin=\"loggregator.doppler\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Adapter Loss Rate",
     "type": "graph",
     "description": "The loss rate of the Syslog Adapters, that is, the total messages dropped as a percentage of the total traffic coming through the Syslog Adapters. Total messages include only logs for bound applications. \n\nThis loss rate is specific to the Syslog Adapters and does not impact the Firehose loss rate. For example, you can suffer lossiness in syslog while not suffering any lossiness in the Firehose.\n\nIndicates that the syslog drains are not keeping up with the number of logs that a syslog-drain-bound app is producing. This likely means that the syslog-drain consumer is failing to keep up with the incoming log volume. \n\nThe recommended scaling indicator is to look at the maximum per minute loss rate over a 5-minute window and scale if the derived loss rate value grows greater than 0.1.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dropped{origin=\"cf-syslog-drain.adapter\"}[$__interval] offset 1m)) / sum(rate(ingress{origin=\"cf-syslog-drain.adapter\"}[$__interval] offset 1m))",
       "legendFormat": "Loss Rate"
      }
     ]
    },
    {
     "title": "RLP Loss Rate",
     "type": "graph",
     "description": "The loss rate of the reverse log proxies (RLP), that is, the total messages dropped as a percentage of the total traffic coming through the reverse log proxy. Total messages include only logs for bound applications. \n\nThis loss rate is specific to the RLP and does not impact the Firehose loss rate. For example, you can suffer lossiness in syslog while not suffering any lossiness in the Firehose.\n\nExcessive dropped messages can indicate that the RLP is overloaded and that the Traffic Controllers need to be scaled. \n\nThe recommended scaling indicator is to look at the maximum per minute loss rate over a 5-minute window and scale if the derived loss rate value grows greater than 10%",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dropped{origin=\"loggregator.rlp\"}[$__interval] offset 1m)) / sum(rate(ingress{origin=\"loggregator.rlp\"}[$__interval] offset 1m))",
       "legendFormat": "Loss Rate"
      }
     ]
    },
    {
     "title": "Syslog Drain Bindings Count",
     "type": "graph",
     "description": "Each Syslog Adapter can handle approximately 250 drain bindings. The recommended initial configuration is a minimum of two Syslog Adapters (to handle approximately 500 drain bindings). A new Adapter instance should be added for each 250 additional drain bindings. \n\nTherefore, the recommended initial scaling indicator is 450 (as a maximum value over a 1-hr window). This indicates the need to scale up to three Adapters from the initial two-Adapter configuration. \n\nPlease note that while `cf-syslog-drain.scheduler.drains` is emitted by each scheduler instance, the metric emitted is the aggregated total number of active drains. Therefore this metric should not be summed across instances, as the total value is already emitted.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "drains{origin=\"cf-syslog-drain.scheduler\"}",
       "legendFormat": "{{index}} drains"
      }
     ]
    }
   ]
  },
  {
   "title": "MySQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Available",
     "type": "graph",
     "description": "The MySQL Server is currently responding to requests, which indicates that the server is running.\n\nUse: This metric is especially useful in single-node mode, where cluster metrics are not relevant. If the server does not emit heartbeats, it is offline.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "_mysql_available{origin=\"mysql\"}",
       "legendFormat": "MySQL Available"
      }
     ]
    },
    {
     "title": "Galera Cluster Status",
     "type": "graph",
     "description": "Shows the primary status of the cluster component that the node is in.\nValues are:\n- Primary = 1\n- Non-primary = 0\n- Disconnected = -1\nSee: https://mariadb.com/kb/en/mariadb/galera-cluster-status-variables/ \n\nUse: Any value other than “Primary” indicates that the node is part of a nonoperational component. This occurs in cases of multiple membership changes that result in a loss of quorum.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "_mysql_galera_wsrep_cluster_status{origin=\"mysql\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Galera Cluster Size",
     "type": "graph",
     "description": "The number of cluster nodes with which each node is communicating normally.\n\nUse: When running in a multi-node configuration, this metric indicates if each member of the cluster is communicating normally with all other nodes.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "_mysql_galera_wsrep_cluster_size{origin=\"mysql\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "MySQL CPU Percent",
     "type": "graph",
     "description": "CPU time being consumed by the MySQL service.\n\nUse: A node that experiences context switching or high CPU usage will become unresponsive. This also affects the ability of the node to report metrics.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "_mysql_performance_cpu_utilization_percent{origin=\"mysql\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "MySQL Connection Rate per Second",
     "type": "graph",
     "description": "Connections per minute made to the server.\n\nUse: If the number of connections drastically changes or if apps are unable to connect, there might be a network or app issue.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(_mysql_net_connections{origin=\"mysql\"}[$__interval] offset 1m)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "MySQL Queries",
     "type": "graph",
     "description": "The number of statements executed by the server over the last 30 seconds.\n\nUse: The server should always be processing some queries. If the server does not process any queries, the server is non-functional.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "_mysql_performance_queries_delta{origin=\"mysql\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Galera Cluster Node Readiness",
     "type": "graph",
     "description": "Shows whether each cluster node can accept queries. Returns only 0 or 1. When this metric is 0, almost all queries to that node fail with the error:\nERROR 1047 (08501) Unknown Command\n\nUse: Discover when nodes of a cluster have been unable to communicate and, thus, unable to accept transactions.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "_mysql_galera_wsrep_ready{origin=\"mysql\"}",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Router",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "Router File Descriptors",
     "type": "graph",
     "description": "The number of file descriptors currently used by the Gorouter job. \n\nUse: Indicates an impending issue with the Gorouter. Without proper mitigation, it is possible for an unresponsive app to eventually exhaust available Gorouter file descriptors and cause route starvation for other apps running on PAS. Under heavy load, this unmitigated situation can also result in the Gorouter losing its connection to NATS and all routes being pruned. \n\nWhile a drop in gorouter.total_routes or an increase in gorouter.ms_since_last_registry_update helps to surface that the issue may already be occurring, alerting on gorouter.file_descriptors indicates that such an issue is impending. \n\nThe Gorouter limits the number of file descriptors to 100,000 per job. Once the limit is met, the Gorouter is unable to establish any new connections. ",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "file_descriptors{origin=\"gorouter\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Time Since Last Route Registration",
     "type": "graph",
     "description": "Time in milliseconds since the last route register was received, emitted per Gorouter instance \n\nUse: Indicates if routes are not being registered to apps correctly. ",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ms_since_last_registry_update{origin=\"gorouter\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Router Errors",
     "type": "graph",
     "description": "The lifetime number of requests completed by the Gorouter VM for HTTP status family 5xx, server errors, emitted per Gorouter instance. \n\nUse: A repeatedly crashing app is often the cause of a big increase in 5xx responses. However, response issues from apps can also cause an increase in 5xx responses. Always investigate an unexpected increase in this metric. ",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(responses_5xx{origin=\"gorouter\"}[1m] offset 1m)",
       "legendFormat": "Resp/sec"
      }
     ]
    },
    {
     "title": "Router Exhausted Connections",
     "type": "graph",
     "description": "The lifetime number of requests that have been rejected by the Gorouter VM due to the Max Connections Per Backend limit being reached across all tried backends. The limit controls the number of concurrent TCP connections to any particular app instance and is configured within PAS. \n\nUse: Indicates that PAS is mitigating risk to other applications by self-protecting the platform against one or more unresponsive applications. Increases in this metric indicate the need to investigate and resolve issues with potentially unresponsive applications. A rapid rate of change upward is concerning and should be assessed further. ",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(backend_exhausted_conns{origin=\"gorouter\"}[1m] offset 1m)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Route Registration Messages Delta",
     "type": "graph",
     "description": "This KPI is based on the following metrics: \n\nroute_emitter.HTTPRouteNATSMessagesEmitted reports the lifetime number of route registration messages sent by the Route Emitter component. The metric is emitted for each Route Emitter.\ngorouter.registry_message.route-emitter reports the lifetime number of route registration messages received by the Gorouter. The metric is emitted for each Gorouter instance.\nDynamic configuration that enables the Gorouter to route HTTP requests to apps is published by the Route Emitter component colocated on each Diego cell to the NATS clustered message bus. All router instances subscribed to this message bus receive the same configuration. (Router instances within an isolation segment receive configuration only for cells in the same isolation segment.) \n\nAs Gorouters prune app instances from the route when a TTL expires, each Route Emitter periodically publishes the routing configuration for the app instances on the same cell. \n\nTherefore, the aggregate number of route registration messages published by all the Route Emitters should be equal to the number of messages received by each Gorouter instance. \n\nUse: A difference in the rate of change of these metrics is an indication of an issue in the control plane responsible for updating the routers with changes to the routing table. \n\nPivotal recommends alerting when the number of messages received per second for a given router instance falls below the sum of messages emitted per second across all Route Emitters. \n\nIf visualizing these metrics on a dashboard, look for increases in the difference between the rate of messages received and sent. If the number of messages received by a Gorouter instance drops below the sum of messages sent by the Route Emitters, this is an indication of a problem in the control plane. ",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(registry_message_route_emitter{origin=\"gorouter\"}[$__interval] offset 1m)",
       "legendFormat": "Routes Emitted {{index}}"
      },
      {
       "expr": "sum(rate(HTTPRouteNATSMessagesEmitted{origin=\"route_emitter\"}[$__interval] offset 1m))",
       "legendFormat": "NATS Messages Emitted"
      }
     ]
    },
    {
     "title": "Route Emitter Time to Sync",
     "type": "graph",
     "description": "Time in ns that the active Route Emitter took to perform its synchronization pass. \n\nUse: Increases in this metric indicate that the Route Emitter may have trouble maintaining an accurate routing table to broadcast to the Gorouters. Tune alerting values to your deployment based on historical data and adjust based on observations over time. The suggested starting point is ≥ 5 for the yellow threshold and ≥ 10 for the critical threshold. Pivotal has observed on its Pivotal Web Services deployment that above 10 s, the BBS may be failing. ",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "RouteEmitterSyncDuration{origin=\"route_emitter\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Routes",
     "type": "graph",
     "description": "The current total number of routes registered with the Gorouter, emitted per Gorouter instance \n\nUse: The aggregation of these values across all Gorouters indicates uptake and gives a picture of the overall growth of the environment for capacity planning. \n\nPivotal also recommends alerting on this metric if the number of routes falls outside of the normal range for your deployment. Dramatic decreases in this metric volume may indicate a problem with the route registration process, such as an app outage, or that something in the route register management plane has failed. \n\nIf visualizing these metrics on a dashboard, gorouter.total_routes can be helpful for visualizing dramatic drops. However, for alerting purposes, the gorouter.ms_since_last_registry_update metric is more valuable for quicker identification of Gorouter issues. Alerting thresholds for gorouter.total_routes should focus on dramatic increases or decreases out of expected range. ",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "total_routes{origin=\"gorouter\"}",
       "legendFormat": "{{index}} routes"
      }
     ]
    },
    {
     "title": "Router Bad Gateway Responses per Second (max)",
     "type": "graph",
     "description": "The lifetime number of bad gateways, or 502 responses, from the Gorouter itself, emitted per Gorouter instance.\nThe Gorouter emits a 502 bad gateway error when it has a route in the routing table and, in attempting to make a connection to the backend, finds that the backend does not exist. \n\nUse: Indicates that route tables might be stale. Stale routing tables suggest an issue in the route register management plane, which indicates that something has likely changed with the locations of the containers. Always investigate unexpected increases in this metric. ",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(bad_gateways{origin=\"gorouter\"}[1m] offset 1m)",
       "legendFormat": "Resp/sec"
      }
     ]
    },
    {
     "title": "Router Latency",
     "type": "graph",
     "description": "The time in milliseconds that the Gorouter takes to handle requests to backend endpoints, which include both applications routable platform system APIs like Cloud Controller and UAA. This is the average round trip response time, which includes router handling. \n\nUse: Indicates how Gorouter jobs in PAS are impacting overall responsiveness. Latencies above 100 ms can indicate problems with the network, misbehaving backends, or the need to scale the Gorouter itself due to ongoing traffic congestion. An alert value on this metric should be tuned to the specifics of the deployment and its underlying network considerations; a suggested starting point is 100 ms. ",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "latency{origin=\"gorouter\"}",
       "legendFormat": "{{index}} latency"
      }
     ]
    },
    {
     "title": "Router Requests per Second",
     "type": "graph",
     "description": "The lifetime number of requests completed by the Gorouter VM, emitted per Gorouter instance \n\nUse: The aggregation of these values across all Gorouters provide insight into the overall traffic flow of a deployment. Unusually high spikes, if not known to be associated with an expected increase in demand, could indicate a DDoS risk. For performance and capacity management, consider this metric a measure of router throughput per job, converting it to requests-per-second, by looking at the delta value of gorouter.total_requests and deriving back to 1s, or gorouter.total_requests.delta)/5, per Gorouter instance. This helps you see trends in the throughput rate that indicate a need to scale the Gorouter instances. Use the trends you observe to tune the threshold alerts for this metric. ",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(total_requests{origin=\"gorouter\"}[5m] offset 1m)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Router CPU",
     "type": "graph",
     "description": "High CPU utilization of the Gorouter VMs can increase latency and cause throughput, or requests per/second, to level-off. Pivotal recommends keeping the CPU utilization within a maximum range of 60-70% for best Gorouter performance. \n\nIf you want to increase throughput capabilities while also keeping latency low, Pivotal recommends scaling the Gorouter while continuing to ensure that CPU utilization does not exceed the maximum recommended range.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "system_cpu_user{exported_job=\"router\"}",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "UAA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failed User Authentications",
     "type": "singlestat",
     "description": "Number of failed user authentication attempts since the last startup.",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 23 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(avg(audit_service_user_authentication_failure_count{origin=\"uaa\"}) by (deployment, exported_job, index))"
      }
     ]
    },
    {
     "title": "UAA Concurrent Requests",
     "type": "graph",
     "description": "The number of requests UAA is currently processing (in-flight requests), emitted per UAA instance. \n\nUse: Indicates how many concurrent requests are currently in flight for the UAA instance. Unusually high spikes, if they are not associated with an expected increase in demand, could indicate a DDoS risk. \n\nFrom performance and load testing of the UAA component, Pivotal has observed that the number of concurrent requests impacts throughput and latency. The UAA Requests In Flight metric helps you see trends in the request rate that may indicate the need to scale UAA instances. Use the trends you observe to tune the threshold alerts for this metric. ",
     "gridPos": { "h": 6, "w": 7, "x": 3, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "server_inflight_count{origin=\"uaa\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "UAA Latency",
     "type": "graph",
     "description": "Time in milliseconds that UAA took to process a request that the Gorouter sent to UAA endpoints. \n\nUse: Indicates how responsive UAA has been to requests sent from the Gorouter. Some operations may take longer to process, such as creating bulk users and groups. It is important to correlate latency observed with the endpoint and evaluate this data in the context of overall historical latency from that endpoint. Unusual spikes in latency could indicate the need to scale UAA VMs. \n\nThis metric is emitted only for the routers serving the UAA system component and is not emitted per isolation segment even if you are using isolated routers. ",
     "gridPos": { "h": 6, "w": 7, "x": 10, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "latency_uaa{origin=\"gorouter\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "UAA Requests per Second",
     "type": "graph",
     "description": "The lifetime number of requests completed by the UAA VM, emitted per UAA instance. This number includes health checks. \n\nUse: For capacity planning purposes, the aggregation of these values across all UAA instances can provide insight into the overall load that UAA is processing. It is recommended to alert on unexpected spikes per UAA instance. Unusually high spikes, if they are not associated with an expected increase in demand, could indicate a DDoS risk and should be investigated. \n\nFor performance and capacity management, look at the UAA Throughput metric as either a requests-completed-per-second or requests-completed-per-minute rate to determine the throughput per UAA instance. This helps you see trends in the throughput rate that may indicate a need to scale UAA instances. Use the trends you observe to tune the threshold alerts for this metric. \n\nFrom performance and load testing of UAA, Pivotal has observed that while UAA endpoints can have different throughput behavior, once throughput reaches its peak value per VM, it stays constant and latency increases. ",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(requests_global_completed_count{origin=\"uaa\"}[$__interval] offset 1m)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "UAA CPU",
     "type": "graph",
     "description": "High CPU utilization of the UAA VMs can increase latency and cause throughput, or requests per/second, to level-off. Pivotal recommends keeping the CPU utilization within a maximum range of 80-90% for best UAA performance. \n\nIf you want to increase throughput capabilities while keeping latency low, Pivotal recommends scaling the UAA VMs and ensuring that CPU utilization does not exceed the maximum recommended range.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "system_cpu_user{exported_job=\"uaa\"}",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  }
 ]
}